/**
 * @file tailwind.config.cjs
 * @brief Tailwind design tokens and source discovery for the Vite build.
 */
module.exports = {
	content: ['./index.html', './src/**/*.{html,ts}'],
	darkMode: 'class',
	theme: {
		extend: {
			fontFamily: {
				mono: ['"Share Tech Mono"', 'monospace'],
				sans: ['"Share Tech"', 'sans-serif'],
				display: ['"Share Tech"', 'sans-serif'],
				'badge-mono': ['"Share Tech Mono"', 'monospace'],
				'field-label': ['"Share Tech"', 'sans-serif'],
				'input-mono': ['"Share Tech Mono"', 'monospace'],
				'unit-annotation': ['"Share Tech Mono"', 'monospace'],
			},
			fontSize: {
				'badge-mono': ['0.625rem', { lineHeight: '1rem', letterSpacing: '0.05em' }],
				'field-label': ['0.6875rem', { lineHeight: '1rem' }],
				'input-mono': ['0.8125rem', { lineHeight: '1.25rem' }],
				'unit-annotation': ['0.625rem', { lineHeight: '1rem' }],
			},
			colors: {
				page: 'var(--bg-page)',
				surface: 'var(--bg-card)',
				'surface-card': 'var(--bg-surface-card)',
				'surface-subtle': 'var(--bg-surface-subtle)',
				'surface-input': 'var(--bg-surface-input)',
				'surface-border': 'var(--border-surface-border)',
				'surface-row': 'var(--bg-surface-row)',
				background: 'var(--bg-background)',
				input: 'var(--bg-input)',
				canvas: 'var(--bg-canvas)',
				'text-main': 'var(--text-main)',
				'text-dim': 'var(--text-dim)',
				'text-output': 'var(--text-output)',
				'text-muted': 'var(--text-muted)',
				border: 'var(--border)',
				'border-input': 'var(--border-input)',
				'accent-amber-overlay': 'var(--accent-amber-overlay)',
				'accent-red-overlay': 'var(--accent-red-overlay)',
				'accent-cyan-overlay': 'var(--accent-cyan-overlay)',
				'neon-red': 'var(--accent-red)',
				'neon-orange': 'var(--accent-orange)',
				'neon-yellow': 'var(--accent-yellow)',
				'neon-green': 'var(--accent-green)',
				'neon-cyan': 'var(--accent-cyan)',
				'neon-blue': 'var(--accent-blue)',
				'neon-purple': 'var(--accent-purple)',
				'surface-recessed': 'var(--bg-surface-recessed)',
				'surface-raised': 'var(--bg-surface-raised)',
				'surface-container': 'var(--bg-surface-subtle)',
				'surface-container-high': 'var(--bg-surface-raised)',
				'surface-bright': 'var(--bg-surface-input)',
				'canvas-plot': 'var(--bg-canvas-plot)',
				'border-hairline': 'var(--border-hairline)',
				'focus-ring': 'var(--focus-ring)',
				'accent-kinematic': 'var(--accent-kinematic)',
				'accent-aero': 'var(--accent-aero)',
				'accent-warning': 'var(--accent-warning)',
				'accent-compare': 'var(--accent-compare)',
				'primary-fixed-dim': 'var(--accent-cyan)',
				'on-surface-variant': 'var(--text-dim)',
				secondary: 'var(--accent-green)',
				'gear-1': 'var(--gear-1)',
				'gear-2': 'var(--gear-2)',
				'gear-3': 'var(--gear-3)',
				'gear-4': 'var(--gear-4)',
				'gear-5': 'var(--gear-5)',
				'gear-6': 'var(--gear-6)',
				'gear-7': 'var(--gear-7)',
				'gear-8': 'var(--gear-8)',
			},
			borderRadius: {
				DEFAULT: '2px',
				sm: '2px',
				md: '2px',
				lg: '4px',
				xl: '8px',
				'2xl': '12px',
				full: '12px',
			},
			spacing: {
				'space-xs': '0.375rem',
				'space-sm': '0.5rem',
			},
		},
	},
};
